// lib/icones.dart
import 'package:flutter/material.dart';

import 'package:flutter/material.dart';

final Map<String, IconData> iconesPorPalavra = {
  'pão': Icons.bakery_dining,
  'leite': Icons.local_drink,
  'arroz': Icons.rice_bowl,
  'feijão': Icons.soup_kitchen,
  'carne': Icons.set_meal,
  'frango': Icons.set_meal,
  'ovo': Icons.egg_alt,
  'tomate': Icons.local_florist,
  'alface': Icons.grass,
  'banana': Icons.energy_savings_leaf,
  'maçã': Icons.apple,
  'suco': Icons.local_cafe,
  'água': Icons.water_drop,
  'café': Icons.coffee,
  // 'queijo': Icons.cheese,
  'chocolate': Icons.cake,
  'pizza': Icons.local_pizza,
  'sorvete': Icons.icecream,
  'bolo': Icons.cake,
  'laranja': Icons.circle, // sem ícone direto, use genérico
  'melancia': Icons.water_drop, // sem ícone direto, use água (ideia)
  'pepino': Icons.grass, // sem ícone direto, use planta
  'batata': Icons.grain, // sem ícone direto, use grão
  'cenoura': Icons.local_florist,
  'uva': Icons.wine_bar,
  'abacaxi': Icons.local_florist,
  'coca': Icons.local_drink,
  'refrigerante': Icons.local_drink,
  'água mineral': Icons.water_drop,
  'cerveja': Icons.sports_bar,
  'vinho': Icons.wine_bar,
  'peixe': Icons.set_meal,
  'camarao': Icons.set_meal,
  'camarão': Icons.set_meal,
  'espinafre': Icons.grass,
  'cebola': Icons.local_florist,
  'alho': Icons.local_florist,
  'pimenta': Icons.local_fire_department,
  'molho': Icons.soup_kitchen,
  'iogurte': Icons.icecream,
  // 'manteiga': Icons.butter,
  'cereal': Icons.breakfast_dining,
  'aveia': Icons.breakfast_dining,
  'macarrao': Icons.set_meal,
  'massa': Icons.set_meal,
  'churrasco': Icons.set_meal,
  'hamburguer': Icons.fastfood,
  'batata frita': Icons.fastfood,
  'salada': Icons.grass,
  'hambúrguer': Icons.fastfood,
  // 'pipoca': Icons.popcorn,
  // 'mel': Icons.honey,
  'cuscuz': Icons.rice_bowl,
  'limão': Icons.local_florist,
  'abacate': Icons.local_florist,
  'café com leite': Icons.coffee,
  'chá': Icons.emoji_food_beverage,
  'coco': Icons.local_florist,
  'pêssego': Icons.local_florist,
  'morango': Icons.local_florist,
  'amendoim': Icons.spa,
  'nozes': Icons.spa,
  'castanha': Icons.spa,
  // 'pipoca': Icons.popcorn,
  'bolo de chocolate': Icons.cake,
  'sanduíche': Icons.fastfood,
  'hamburguer': Icons.fastfood,
  'bolo de cenoura': Icons.cake,
  'pizza': Icons.local_pizza,
  'feijoada': Icons.soup_kitchen,
  'churrasco': Icons.set_meal,
  'lasanha': Icons.set_meal,
  'sushi': Icons.set_meal,
  'macarrão': Icons.set_meal,
  'espaguete': Icons.set_meal,
  'wrap': Icons.fastfood,
  'taco': Icons.fastfood,
  'nachos': Icons.fastfood,
  'salame': Icons.set_meal,
  'biscoito': Icons.cookie,
  'cookie': Icons.cookie,
  'creme': Icons.icecream,
  'iogurte': Icons.icecream,
  'água de coco': Icons.local_florist,
  'requeijão': Icons.dining,
  'pepperoni': Icons.local_pizza,
  'mousse': Icons.icecream,
  'quiche': Icons.cake,
  'sorvete de creme': Icons.icecream,
  'água com gás': Icons.water,
  'café espresso': Icons.coffee,
  'capuccino': Icons.coffee,
};
